name: Build and Test ScreenPipe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone ScreenPipe Repository
        run: git clone https://github.com/mediar-ai/screenpipe.git

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            pkg-config \
            ffmpeg \
            libavcodec-dev \
            libavformat-dev \
            libavutil-dev \
            libswscale-dev \
            libasound2-dev \
            libdbus-1-dev \
            libxcb1-dev \
            libxcb-render0-dev \
            libxcb-shape0-dev \
            libxcb-xfixes0-dev \
            libtesseract-dev \
            libssl-dev \
            cmake \
            build-essential \
            libx11-dev \
            libxi-dev \
            libxext-dev \
            libxtst-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxdo-dev

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: aarch64-unknown-linux-gnu

      - name: Build ScreenPipe
        working-directory: screenpipe
        run: cargo build --release
