name: run macos

on:
  push:

jobs:
  record:
    runs-on: macos-latest
    steps:
      - name: Take screenshot for debug
        run: screencapture -x screenshot.png

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshot.png


