name: run win10

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  debug:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - name: Setup tmate
      uses: mxschmitt/action-tmate@v3

